name: Trigger Pull Request Workflow

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Subworkflow
        uses: thunsudamn/workflows-action/.github/workflows/clean-up.yaml@main 
        with:
          pr_number: ${{ github.event.inputs.pr_number }}
